inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# Offense count: 34
Metrics/AbcSize:
  Max: 220

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 513

Metrics/ModuleLength:
  Max: 600

# Offense count: 13
Metrics/CyclomaticComplexity:
  Max: 31

# Offense count: 49
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 116

# Offense count: 47
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 224

# Offense count: 13
Metrics/PerceivedComplexity:
  Max: 35

# This cop should be moved to the yast rubocop style.
# Note that frozen string literals was not finally the default in ruby 3,
# see https://github.com/rubocop/rubocop/issues/7197.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - testsuite/tests/*.rb

Style/FileName:
  Exclude:
    - src/clients/nfs-client.rb
    - src/clients/nfs-client4part.rb
    - src/modules/Nfs.rb
    - src/modules/NfsOptions.rb

Style/MethodName:
  Exclude:
    - src/clients/nfs-client4part.rb
    - src/clients/nfs.rb
    - src/include/nfs/routines.rb
    - src/include/nfs/ui.rb
    - src/include/nfs/wizards.rb
    - src/modules/Nfs.rb

Style/VariableName:
  Exclude:
    - testsuite/tests/*.rb
