# Rubocop style configuration
#
# Following
# https://github.com/SUSE/style-guides/blob/master/Ruby.md

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Is there any justification for "aligned" which is the default?
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false
