# Rubocop style configuration
#
# Following
# https://github.com/SUSE/style-guides/blob/master/Ruby.md

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# YCP Killer used rockets
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false
